base_url = "127.0.0.1"
# theme = "zola.386"

default_language = "en"
title = "ETHICS.exe"
description = ""

#highlight_code = true
compile_sass = true
#generate_rss = true
build_search_index = true

taxonomies = [
  {name="categories", rss=true},
  {name="tags", rss=true},
]


[extra]
author = "Association for Computing Machinery (ACM)"
year = "2018"

keywords = "zola, theme, retro, hacking"
theme_color = "#000084"
zola386_menu = [
  {path="", name="Home"},
  {path="categories", name="Categories"},
  #{path="tags", name="Tags"},
  #{path="about", name="About"},
]

### THIRD PARTY
# google_analytics = "UA-012345-67"
# disqus = "disqus-user"

### SOCIAL MEDIA
image = "https://raw.githubusercontent.com/lopes/zola.386/master/screenshot.png"
twitter_user = "theofficialacm"
linkedin_user = "association-for-computing-machinery"
github_user = "gitster"
# gitlab_user = ""

### I18N WORDS
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_author = "Author"
label_date = "Date"
label_taxonomy = "Taxonomy"
label_reading = "Reading time"
label_read_more = "Read more"
